### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by ghost** [alvinlal/matrice#1]
I believe `Matrices` is the plural form of `Matrix`. I mean singular form is `Matrix` rather than `Matrice`.

**Comment by ghost** [comment]
ok. got it. You decided to name your library `Matrice`.  :)
Ignore my grammar policing.

**Comment by alvinlal** [comment]
thanks for the issue @viveketic , there is no word such as matrice ,matrix is indeed the singular name 😄
